name: Push-to-EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: echo npm install

    - name: Build da Aplicação
      run: npm run build

    - name: Listar Tudo Depois do INSTALL e DEPLOY
      run: ls -la

    - name: Copy files with SSH
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        RGS: "-rltgoDzvO --delete"
        SOURCE: "./dist/"
        REMOTE_HOST: ${{secrets.REMOTE_HOST}}
        REMOTE_USER: ${{secrets.REMOTE_USER}}
        TARGET: ${{secrets.TARGET_DIR}}
        # EXCLUDE: "/dist/, /node_modules/, **.env, rebuild_app.sh, watcher.sh"





